num1 = int(input('insira o 1º numero: '))
num2 = int(input('insira o 2º numero: '))
num3 = int(input('insira o 3º numero: '))
x = min(num1, num2, num3)
y = max(num1, num2, num3)
print('O menor numero é o: {}'.format(x))
print('O maior numero é o: {}'.format(y))
