nome = str(input('Insira o seo nome completo: ')).strip()
print(nome.upper())
print(nome.lower())
qtd = nome.split()
letras = len(qtd[0])
num = "".join(qtd)
print('o numero de letras é: ', len(num))
print('O numero de letras é: ', len(nome)-nome.count(' '))
print('O seu primeiro nome é {} e tem {} letras'.format(qtd[0], letras))
